#!/bin/bash

echo Starting nerva-wallet-rpc

cd /binaries

./nerva-wallet-rpc --wallet-dir /nerva/wallets --rpc-bind-ip 0.0.0.0 --rpc-bind-port 19566 --rpc-login nerva:nerva --daemon-ssl disabled \
--rpc-access-control-origins http://localhost,http://localhost:19566,http://localhost:17500 --rpc-auth-basic --confirm-cleartext-auth --trusted-daemon --confirm-external-bind \
--log-level 3 --log-file /nerva/nerva-wallet-rpc.log --detach "${@}"
