#!/bin/bash

check_aesni

if [ $? -eq 0 ]; then
    prog=nervad-noaes
else
    prog=nervad-aes
fi

echo Starting ${prog}

cd /binaries

./${prog} --p2p-bind-ip 0.0.0.0 --p2p-bind-port 17565 --rpc-bind-ip 0.0.0.0 --rpc-bind-port 17566 \
--confirm-external-bind --quicksync /nerva/quicksync.raw --data-dir /nerva/blockchain --log-file /nerva/nervad.log --detach "${@}"
